<template>
  <main class="docs-home">
    <section class="hero">
      <p class="hero__eyebrow">Company Shared UI</p>
      <h1>组件库文档工作台</h1>
      <p class="hero__desc">
        这个站点用于展示公共包结构、AI manifest 路径，以及首个公共导出组件的用法示例。
      </p>
    </section>

    <section class="grid">
      <article v-for="pkg in packages" :key="pkg.name" class="card">
        <h2>{{ pkg.name }}</h2>
        <p class="card__path">{{ pkg.path }}</p>
        <p class="card__desc">文档：{{ pkg.docs }}</p>
        <p class="card__desc">AI 清单：{{ pkg.manifest }}</p>
      </article>
    </section>

    <section class="card demo">
      <h2>BaseExportButton 示例</h2>
      <p class="card__desc">
        左边按钮演示前端 Excel 导出，右边按钮演示通过 blob 下载文本文件。
      </p>
      <div class="demo__actions">
        <BaseExportButton :excel-options="excelOptions" />
        <BaseExportButton
          plain
          label="导出文本示例"
          file-name="docs-demo.txt"
          :request-handler="createMockExportRequest"
        />
      </div>
    </section>
  </main>
</template>

<script setup lang="ts">
import { BaseExportButton } from '@hbdlzy/ui-core'
import type { ExcelExportColumn } from '@hbdlzy/ui-core'
import libraryManifest from '../../../library.manifest.json'

interface DemoExportRow {
  name: string
  department: string
  createdAt: string
}

const packages = libraryManifest.workspace.packages

const columns: Array<ExcelExportColumn<DemoExportRow>> = [
  { label: '姓名', key: 'name', width: 16 },
  { label: '部门', key: 'department', width: 18 },
  { label: '创建时间', key: 'createdAt', width: 22 }
]

const excelOptions = {
  fileName: '文档站导出示例',
  sheetName: '导出示例',
  columns,
  data: [
    { name: '张三', department: '调度中心', createdAt: '2026-04-21 09:30:00' },
    { name: '李四', department: '运营中心', createdAt: '2026-04-21 10:15:00' }
  ]
}

const createMockExportRequest = async () => {
  return {
    data: new Blob(
      ['BaseExportButton docs demo.\n', 'This file is generated by the docs app.\n'],
      { type: 'text/plain;charset=utf-8' }
    ),
    headers: {}
  }
}
</script>

<style scoped>
.docs-home {
  min-height: 100vh;
  padding: 32px;
  background:
    radial-gradient(circle at top left, rgba(29, 99, 255, 0.14), transparent 32%),
    linear-gradient(180deg, #f4f8ff 0%, #ffffff 100%);
  color: var(--company-color-text-main);
}

.hero {
  max-width: 760px;
  margin-bottom: 24px;
}

.hero__eyebrow {
  margin: 0 0 8px;
  color: var(--company-color-primary);
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.hero h1 {
  margin: 0 0 12px;
  font-size: 36px;
}

.hero__desc {
  margin: 0;
  color: var(--company-color-text-secondary);
  line-height: 1.8;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 16px;
  margin-bottom: 16px;
}

.card {
  padding: 20px;
  border: 1px solid var(--company-color-border);
  border-radius: var(--company-radius-lg);
  background: var(--company-color-surface);
  box-shadow: var(--company-shadow-card);
}

.card h2 {
  margin: 0 0 10px;
  font-size: 20px;
}

.card__path,
.card__desc {
  margin: 0 0 8px;
  color: var(--company-color-text-secondary);
  line-height: 1.7;
  word-break: break-all;
}

.demo__actions {
  display: flex;
  gap: 12px;
  margin-top: 16px;
}
</style>
